{{- if and .Values.monitoring.prometheus.enabled .Values.global.nvidia.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nvidia-gpu-rules
  labels:
    {{- include "srt-model-quantizing.labels" . | nindent 4 }}
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: nvidia.gpu.rules
    rules:
    - alert: NvidiaGPUHighMemoryUsage
      expr: DCGM_FI_DEV_FB_USED / DCGM_FI_DEV_FB_TOTAL > 0.90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU memory usage is high
        description: GPU {{ $labels.gpu }} on {{ $labels.instance }} has high memory usage (> 90%) for more than 5 minutes

    - alert: NvidiaGPUHighTemperature
      expr: DCGM_FI_DEV_GPU_TEMP > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU temperature is high
        description: GPU {{ $labels.gpu }} on {{ $labels.instance }} has high temperature (> 80°C) for more than 5 minutes

    - alert: NvidiaGPUPowerUsage
      expr: DCGM_FI_DEV_POWER_USAGE / DCGM_FI_DEV_POWER_LIMIT > 0.90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU power usage is high
        description: GPU {{ $labels.gpu }} on {{ $labels.instance }} has high power usage (> 90%) for more than 5 minutes

    - alert: NvidiaGPUUtilization
      expr: DCGM_FI_DEV_GPU_UTIL > 95
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: GPU utilization is very high
        description: GPU {{ $labels.gpu }} on {{ $labels.instance }} has very high utilization (> 95%) for more than 15 minutes

    - alert: NvidiaGPUEccError
      expr: DCGM_FI_DEV_ECC_DBE_VOL_TOTAL > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: GPU ECC double-bit error detected
        description: GPU {{ $labels.gpu }} on {{ $labels.instance }} has detected ECC double-bit errors

    - alert: NvidiaGPUHealthStatus
      expr: DCGM_FI_DEV_HEALTH_STATUS > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: GPU health status is not optimal
        description: GPU {{ $labels.gpu }} on {{ $labels.instance }} has reported a health issue

    # Additional GPU monitoring rules
    - alert: NvidiaGPUMemoryBandwidthSaturation
      expr: DCGM_FI_DEV_MEM_COPY_UTIL > 90
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: GPU memory bandwidth saturation
        description: GPU {{ $labels.gpu }} memory bandwidth utilization is above 90% for more than 10 minutes

    - alert: NvidiaGPUPCIeErrors
      expr: DCGM_FI_DEV_PCIE_REPLAY_COUNTER > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU PCIe errors detected
        description: GPU {{ $labels.gpu }} has PCIe replay errors

    - alert: NvidiaGPUThermalThrottling
      expr: DCGM_FI_DEV_POWER_VIOLATION > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU thermal throttling detected
        description: GPU {{ $labels.gpu }} is experiencing thermal throttling

    - alert: NvidiaGPUMemoryErrorsDetected
      expr: DCGM_FI_DEV_FB_ERRORS > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: GPU memory errors detected
        description: GPU {{ $labels.gpu }} has detected memory errors

    - alert: NvidiaGPULowUtilizationHighMemory
      expr: DCGM_FI_DEV_GPU_UTIL < 30 and (DCGM_FI_DEV_FB_USED / DCGM_FI_DEV_FB_TOTAL > 0.8)
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: GPU low utilization with high memory usage
        description: GPU {{ $labels.gpu }} has low utilization (< 30%) but high memory usage (> 80%) for more than 30 minutes

    - alert: NvidiaGPUFrequencyReduction
      expr: DCGM_FI_DEV_SM_CLOCK < DCGM_FI_DEV_SM_CLOCK_MAX * 0.7
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: GPU frequency significantly reduced
        description: GPU {{ $labels.gpu }} clock speed is reduced by more than 30% for over 10 minutes

    # Model inference specific rules
    - alert: ModelInferenceLatencyHigh
      expr: rate(model_inference_time_seconds_sum[5m]) / rate(model_inference_time_seconds_count[5m]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Model inference latency is high
        description: Average inference time is above 1 second for the last 5 minutes

    - alert: ModelThroughputLow
      expr: rate(model_inference_requests_total[5m]) < 10
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Model throughput is low
        description: Model inference throughput is below 10 requests per second for 15 minutes
{{- end }} 