apiVersion: v2
name: srt-model-quantizing
description: A Helm chart for SRT Model Quantizing Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: "15.10.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.32.2"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: elasticsearch
    version: "7.17.3"
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kibana
    version: "7.17.3"
    repository: https://helm.elastic.co
    condition: kibana.enabled
maintainers:
  - name: SolidRusT Networks
    email: support@solidrust.net 