apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: srt-model-quantizing

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 4Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 8Gi

- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

commonLabels:
  environment: production

images:
- name: srt-model-quantizing/frontend
  newTag: latest
- name: srt-model-quantizing/api
  newTag: latest

configMapGenerator:
- name: srt-model-quantizing-config
  behavior: merge
  literals:
  - ENV=production
  - LOG_LEVEL=INFO
  - METRICS_ENABLED=true
  - TRACING_ENABLED=true 