global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'srt-model-quantizing'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'srt-model-quantizing'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['dcgm-exporter:9400']

  - job_name: 'triton'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['triton:8002']

  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['otel-collector:8889']
