apiVersion: v1
kind: ConfigMap
metadata:
  name: srt-model-quantizing-config
  namespace: srt-model-quantizing
data:
  STORAGE_BASE_PATH: "/data/storage"
  STORAGE_MODELS_PATH: "/data/storage/models"
  STORAGE_METRICS_PATH: "/data/storage/metrics"
  STORAGE_GRAFANA_PATH: "/data/storage/grafana"
  STORAGE_MAX_SIZE_GB: "100"
  STORAGE_CLEANUP_AGE_DAYS: "30"
  STORAGE_MIN_REQUESTS: "10"
  STORAGE_REQUEST_TIMEFRAME_DAYS: "7"
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  PROMETHEUS_MULTIPROC_DIR: "/tmp"
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "all"
  GPU_MEMORY_FRACTION: "0.9"
  OTEL_SERVICE_NAME: "srt-model-quantizing"
  OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: srt-model-quantizing
data:
  nginx.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            expires 1h;
            add_header Cache-Control "public, no-transform";
        }
        
        location /api/ {
            proxy_pass http://api:8000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    } 