apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- storage.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: srt-model-quantizing
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml=../../prometheus/prometheus.yml
- name: grafana-config
  files:
  - ../../grafana/provisioning/dashboards/dashboards.yml
  - ../../grafana/provisioning/datasources/datasources.yml 