apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: srt-model-quantizing

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 2Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 4Gi

- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

commonLabels:
  environment: development

images:
- name: srt-model-quantizing/frontend
  newTag: dev
- name: srt-model-quantizing/api
  newTag: dev

configMapGenerator:
- name: srt-model-quantizing-config
  behavior: merge
  literals:
  - ENV=development
  - LOG_LEVEL=DEBUG
  - METRICS_ENABLED=true
  - TRACING_ENABLED=true 